### ISSUE TITLE
permissison issue when installing the enviroment

### ISSUE THREAD

**Issue by yding25** [chuangg/OPEn#1]
Hi,

How could I get permission when installing the environment?

**Comment by chuangg** [comment]
Hi,
What do you mean by permission?

**Comment by yding25** [comment]
> Hi, What do you mean by permission?

Thanks for your reply.
After I input 'git clone https://github.ibm.com/Abhi-B/gym-tdw.git', it shows 'Username for https://github.ibm.com'.
I do not have such a **username** and **password** for the **IBM account**.
Is there any permission issue?

**Comment by abhi1092** [comment]
That is the wrong GitHub URL. You will have to use this 
`git clone https://github.com/chuangg/OPEn.git&&cd OPEn/`
I have updated the Readme too
